name: Auto Update Submodule on PR

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - dev

jobs:
  auto-update-submodule:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set git config
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Update submodule to latest dev
        run: |
          cd sub
          git fetch origin dev
          git checkout -B dev origin/dev
          cd ..
          git add sub
          if git diff --cached --quiet; then
            echo "Submodule already up-to-date."
            exit 0
          fi
          git commit -m "chore(submodule): Update submodule 'sub' to latest dev"
          git push