name: Auto Update Submodule on PR

on:
  # dev 브랜치를 대상으로 하는 PR이 생성되거나, 업데이트될 때 실행하도록 변경
  pull_request:
    types: [opened, synchronize]
    branches:
      - dev

jobs:
  auto-update-submodule:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Checkout PR Branch'
        uses: actions/checkout@v4
        with:
          # pull_request 이벤트에서는 github.head_ref가 정상적으로 동작합니다.
          ref: ${{ github.head_ref }}
          submodules: 'recursive'

      - name: 'Update Submodule and Commit'
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git submodule update --remote p
          if [[ -z $(git status -s) ]]; then
            echo "Submodule is already up-to-date."
            exit 0
          fi
          echo "Submodule outdated. Committing new version..."
          git add p
          git commit -m "chore(submodule): Update submodule 'p' to latest"
          git push