name: Auto Update Submodule on PR

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - dev

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.SUB_TOKEN }}
      #      - name: Set git config
      #        run: |
      #          git config user.name "${{ github.actor }}"
      #          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
      #
      - name: Update submodule to latest dev
        run: |
          eval `ssh-agent -s`

          echo "${{ secrets.SUB_TOKEN }}" | ssh-add -
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}
          git add --all
          git commit -m "update: GitHub Actions - update translations" || echo "No changes to commit"
          git push